export const ERROR_CODES = {
  // 401
  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  REVOKED_TOKEN: 'REVOKED_TOKEN',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',

  // 403
  TENANT_VIOLATION: 'TENANT_VIOLATION',
  ROLE_DENIED: 'ROLE_DENIED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SCOPE_EXCEEDED: 'SCOPE_EXCEEDED',
  IMPERSONATION_BLOCKED: 'IMPERSONATION_BLOCKED',

  // 400
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // 404
  NOT_FOUND: 'NOT_FOUND',

  // 429
  RATE_LIMITED: 'RATE_LIMITED',

  // 500
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
